artifacts_root: artifacts

base_model:
  root_dir: artifacts/model
  base_model_path: artifacts/model/base_model.h5
  updated_base_model_path: artifacts/model/custom_model.h5

training:
  root_dir: artifacts/train
  trained_model_path: artifacts/train/model.h5
